SacPlan/Models/Meeting.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace SacPlan.Models
{
    public class Meeting
    {
        public int MeetingID { get; set; }

        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        [Display(Name = "Meeting Date")]
        public DateTime MeetingDate { get; set; }

        [Required]
        public string Conductor { get; set; }

        [Required]
        public string Presiding { get; set; }

        [Required]
        public string Invocation { get; set; }

        [Required]
        public string Benediction { get; set; }

        //songs
        [Required, Range(1, 341)]
        [Display(Name = "Opening Hymn")]
        public int OpeningHymn { get; set; }

        [Required, Range(1, 341)]
        [Display(Name = "Sacrament Hymn")]
        public int SacramentHymn { get; set; }

        [Display(Name = "Intermediate Hymn")]
        public int IntermediateHymn { get; set; }

        [Required, Range(1, 341)]
        [Display(Name = "Closing Hymn")]
        public int ClosingHymn { get; set; }

        public ICollection<Speaker> Speakers { get; set; }

    }
}

SacPlan/Controllers/MeetingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SacPlan.Data;
using SacPlan.Models;

namespace SacPlan.Controllers
{
    public class MeetingsController : Controller
    {
        private readonly SacPlanContext _context;

        public MeetingsController(SacPlanContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index(
            string sortOrder,
            string currentFilter,
            string searchString,
            int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;
            var meetings = from m in _context.Meetings
                           select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                meetings = meetings.Where(s => s.Conductor.Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name_desc":
                    meetings = meetings.OrderByDescending(s => s.Conductor);
                    break;
                case "Date":
                    meetings = meetings.OrderBy(s => s.MeetingDate);
                    break;
                case "date_desc":
                    meetings = meetings.OrderByDescending(s => s.MeetingDate);
                    break;
                default:
                    meetings = meetings.OrderBy(s => s.Conductor);
                    break;
            }
            int pageSize = 10;

            return View(await PaginatedList<Meeting>.CreateAsync(meetings.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        // GET: Meetings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var meeting = await _context.Meetings
                .Include(s => s.Speakers)
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.MeetingID == id);
            if (meeting == null)
            {
                return NotFound();
            }

            return View(meeting);
        }

        // GET: Meetings/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Meetings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MeetingID,MeetingDate,Conductor,Presiding,Invocation,Benediction,OpeningHymn,SacramentHymn,IntermediateHymn,ClosingHymn")] Meeting meeting)
        {
            if (ModelState.IsValid)
            {
                _context.Add(meeting);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(meeting);
        }

        // GET: Meetings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var meeting = await _context.Meetings.FindAsync(id);
            if (meeting == null)
            {
                return NotFound();
            }
            return View(meeting);
        }

        // POST: Meetings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MeetingID,MeetingDate,Conductor,Presiding,Invocation,Benediction,OpeningHymn,SacramentHymn,IntermediateHymn,ClosingHymn")] Meeting meeting)
        {
            if (id != meeting.MeetingID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(meeting);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MeetingExists(meeting.MeetingID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(meeting);
        }

        // GET: Meetings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var meeting = await _context.Meetings
                .FirstOrDefaultAsync(m => m.MeetingID == id);
            if (meeting == null)
            {
                return NotFound();
            }

            return View(meeting);
        }

        // POST: Meetings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var meeting = await _context.Meetings.FindAsync(id);
            _context.Meetings.Remove(meeting);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MeetingExists(int id)
        {
            return _context.Meetings.Any(e => e.MeetingID == id);
        }
    }
}

SacPlan/Views/Meetings/Create.cshtml
@model SacPlan.Models.Meeting

@{
    ViewData["Title"] = "Create Meeting";
}

<h1>Create Meeting</h1>

<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MeetingDate" class="control-label"></label>
                <input asp-for="MeetingDate" class="form-control" />
                <span asp-validation-for="MeetingDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Presiding" class="control-label"></label>
                <input asp-for="Presiding" class="form-control" />
                <span asp-validation-for="Presiding" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Conductor" class="control-label"></label>
                <input asp-for="Conductor" class="form-control" />
                <span asp-validation-for="Conductor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OpeningHymn" class="control-label"></label>
                <input asp-for="OpeningHymn" class="form-control" />
                <span asp-validation-for="OpeningHymn" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Invocation" class="control-label"></label>
                <input asp-for="Invocation" class="form-control" />
                <span asp-validation-for="Invocation" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="SacramentHymn" class="control-label"></label>
                <input asp-for="SacramentHymn" class="form-control" />
                <span asp-validation-for="SacramentHymn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <span style="margin:30px 0px;padding:5px; border-radius:3px;background:#ffd800;color:#000">To manager the speakers, you need to create the metting.</span>
            </div>
            <div class="form-group">
                <label asp-for="IntermediateHymn" class="control-label"></label>
                <input asp-for="IntermediateHymn" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="ClosingHymn" class="control-label"></label>
                <input asp-for="ClosingHymn" class="form-control" />
                <span asp-validation-for="ClosingHymn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Benediction" class="control-label"></label>
                <input asp-for="Benediction" class="form-control" />
                <span asp-validation-for="Benediction" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="accbtn1" />
            </div>
        </form>
    </div>
</div>

<div>
    <a  class="accbtn2" asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SacPlan/Views/Meetings/Delete.cshtml
@model SacPlan.Models.Meeting

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete - Meeting</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MeetingDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MeetingDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Presiding)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Presiding)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Conductor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Conductor)
        </dd>

        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OpeningHymn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OpeningHymn)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Invocation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Invocation)
        </dd>


        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SacramentHymn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SacramentHymn)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IntermediateHymn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IntermediateHymn)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ClosingHymn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ClosingHymn)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Benediction)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Benediction)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="MeetingID" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index"  class="accbtn2">Back to List</a>
    </form>
</div>

SacPlan/Views/Meetings/Details.cshtml
@model SacPlan.Models.Meeting

@{
    ViewData["Title"] = "Details";
}

<h1>Details - Meeting</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.MeetingDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.MeetingDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Presiding)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Presiding)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Conductor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Conductor)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.OpeningHymn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.OpeningHymn)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Invocation)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Invocation)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SacramentHymn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SacramentHymn)
        </dd>
        <dt class="col-sm-2">
            Speakers
        </dt>
        <dd class="col-sm-10">
            <table class="table">
                <tr>
                    <th>Full Name</th>
                    <th>Topic</th>
                    <th>Order</th>
                </tr>
                @foreach (var item in Model.Speakers)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.FullName)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Topic)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Order)
                        </td>
                    </tr>
                }
            </table>
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IntermediateHymn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IntermediateHymn)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.ClosingHymn)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.ClosingHymn)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Benediction)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Benediction)
        </dd>
    </dl>  
</div>
<div style="margin-top:20px">
    <a asp-action="Edit" class="accbtn2" asp-route-id="@Model.MeetingID">Edit</a> |
    <a asp-action="Index" class="accbtn2">Back to List</a>
</div>

SacPlan/Views/Meetings/Edit.cshtml
@model SacPlan.Models.Meeting
@{
    ViewData["Title"] = "Edit";
}
<h1>Edit - Meeting</h1>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input id="meetingID" type="hidden" asp-for="MeetingID" />
            <div class="form-group">
                <label asp-for="MeetingDate" class="control-label"></label>
                <input asp-for="MeetingDate" class="form-control" />
                <span asp-validation-for="MeetingDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Presiding" class="control-label"></label>
                <input asp-for="Presiding" class="form-control" />
                <span asp-validation-for="Presiding" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Conductor" class="control-label"></label>
                <input asp-for="Conductor" class="form-control" />
                <span asp-validation-for="Conductor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="OpeningHymn" class="control-label"></label>
                <input asp-for="OpeningHymn" class="form-control" />
                <span asp-validation-for="OpeningHymn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Invocation" class="control-label"></label>
                <input asp-for="Invocation" class="form-control" />
                <span asp-validation-for="Invocation" class="text-danger"></span>
            </div>


            <div class="form-group">
                <label asp-for="SacramentHymn" class="control-label"></label>
                <input asp-for="SacramentHymn" class="form-control" />
                <span asp-validation-for="SacramentHymn" class="text-danger"></span>
            </div>

            <div id="speakersGroup" class="form-group">
                <input id="seeSpeaker" type="button" value="Manager Speakers" class="accbtn1" />
            </div>

            <div class="form-group">
                <label asp-for="IntermediateHymn" class="control-label"></label>
                <input asp-for="IntermediateHymn" class="form-control" />
            </div>
            <div class="form-group">
                <label asp-for="ClosingHymn" class="control-label"></label>
                <input asp-for="ClosingHymn" class="form-control" />
                <span asp-validation-for="ClosingHymn" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Benediction" class="control-label"></label>
                <input asp-for="Benediction" class="form-control" />
                <span asp-validation-for="Benediction" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="accbtn1" />
            </div>
        </form>
    </div>
</div>
<div>
    <a   class="accbtn2" asp-action="Index">Back to List</a>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SacPlan/Views/Meetings/Index.cshtml
@model PaginatedList<SacPlan.Models.Meeting>


@{
    ViewData["Title"] = "Index";
}
<h1><a href="./" style="font-size:15px;color:#ffffff">Home /</a> Meetings</h1>
<p>
    <a asp-action="Create" class="accbtn1">New Meeting</a>
</p>
<form asp-controller="Meetings" asp-action="Index" method="get" class="float-right">
<div class="form-actions no-color">
    <p>
        Find by name: <input type="text" name="SearchString" value="@ViewData["currentFilter"]" />
        <input type="submit" value="Search"  class="accbtn2" /> |
        <a asp-action="Index" class="btn">Back to Full List</a>
    </p>
</div>
</form>

<table class="table">
    <thead>
        <tr>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["DateSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Meeting Date</a>
            </th>
            <th>
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Conducting</a>
            </th>
            <th>
                Presiding
            </th>
            <th>
                Invocation
            </th>
            <th>
                Benediction
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.MeetingDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Conductor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Presiding)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Invocation)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Benediction)
            </td>
            <td>
                <a asp-action="Details" asp-route-id="@item.MeetingID" class="accbtn2">Details</a> |
                <a asp-action="Edit" asp-route-id="@item.MeetingID" class="accbtn2">Edit</a> |
                <a asp-action="Delete" asp-route-id="@item.MeetingID" class="accbtn2">Delete</a>
            </td>
        </tr>
        }
    </tbody>
</table>
@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
    class="accbtn2 @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="accbtn2 float-right @nextDisabled">
    Next
</a>